### ISSUE TITLE
Can you add other appearance like Plasma stype, Icons etc.?

### ISSUE THREAD

**Issue by vivekmiyani** [mkole/KDE-Plasma#1]
As your screenshots contains many themes which this repo is lacking of.
So, Can you add below appearance themes:

- [x] Kvantum theme
- [x] Latte dock theme
- [x] Plasma style
- [x] Colors scheme
- [x] Window decoration (aurorae)
- [x] Icons
- [x] Task switcher
- [x] GTK Theme

**Comment by orchyn** [comment]
> As your screenshots contains many themes which this repo is lacking of.
> So, Can you add below appearance themes:
> 
>     * [x]  Kvantum theme
> 
>     * [ ]  Latte dock theme
> 
>     * [ ]  Plasma style
> 
>     * [ ]  Colors scheme
> 
>     * [x]  Window decoration (aurorae)
> 
>     * [ ]  Icons
> 
>     * [ ]  Task switcher

**Latte dock theme:** I'm using default theme,
**Task switcher:** Default (Large Icons),

**_Color scheme:_** will be uploaded soon.

**Comment by vivekmiyani** [comment]
One question: Do global theme makes any difference, as we can set each themes from settings? (If yes then can you please provide that as well if you have one?).

**Comment by orchyn** [comment]
No, it doesn't (if you use the files from this repo).

**Comment by orchyn** [comment]
> As your screenshots contains many themes which this repo is lacking of.
> So, Can you add below appearance themes:
> 
>     * [ ]  GTK Theme

Hey,

See https://github.com/mkole/XFCE/tree/main/GTK2(3)/Rea-Light

**Comment by vivekmiyani** [comment]
Thanks 😃

**Comment by Amarjit3** [comment]
Is the Plasma style also finished? Thanks in advance!

**Comment by orchyn** [comment]
> Is the Plasma style also finished? Thanks in advance!

Hi,

Sorry for the late replay. I'll upload Plasma styles today.

**Comment by orchyn** [comment]
Here you go: https://github.com/mkole/KDE-Plasma/tree/master/Plasma%20Themes

**Comment by vivekmiyani** [comment]
Hey @mkole thanks for updating!

**Comment by orchyn** [comment]
> Hey @mkole thanks for updating!

Hi. No problem. 

Have you checked this icon pack: https://github.com/yeyushengfan258/BigSur-icon-theme ?

**Comment by orchyn** [comment]
> As your screenshots contains many themes which this repo is lacking of.
> So, Can you add below appearance themes:
>
>     * [ ]  Icons
> 

I highly recommend  **yeyushengfan258**'s icon theme.
